import type { PostType } from '@/types/types';

export const POSTS: PostType[] = [
  {
    id: '1',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '2',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/blog-featured.jpg',
  },
  {
    id: '3',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '4',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '5',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '6',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '7',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '8',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
];
