name: Client blog app
run-name: Client blog tests
on: 
  push:
    branches: [ main, client-blog ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run Jest
        run: yarn test

      - name: Run Cypress
        run: yarn cypress